import { NextRequest, NextResponse } from 'next/server';
import { mockStudents } from '@/data/mockData';

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const studentId = searchParams.get('studentId') || 's-1042';

  const student = mockStudents.find((s) => s.id === studentId);
  if (!student) {
    return new NextResponse('Student not found', { status: 404 });
  }

  // Generate plain text / printable resume format
  const resumeText = `================================================================================
${student.name.toUpperCase()}
${student.department} | Roll No: ${student.rollNumber} | CGPA: ${student.cgpa}
Email: ${student.email} | Phone: ${student.phone}
GitHub: ${student.externalProfiles.github} | LinkedIn: ${student.externalProfiles.linkedin}
================================================================================

EXECUTIVE SUMMARY
Systems and full-stack software engineer with deep expertise in TypeScript, Go, and PostgreSQL.
Career Readiness Score: ${student.careerReadinessScore}/100 | Attendance: ${student.attendancePercentage}%

--------------------------------------------------------------------------------
CORE TECHNICAL COMPETENCIES
${student.skills.map((s) => `• ${s.name} (${s.level}) - Verified: ${s.verified ? 'Yes' : 'No'}`).join('\n')}

--------------------------------------------------------------------------------
FEATURED PROJECTS
${student.projects
  .map(
    (p) => `* ${p.title}
  Tech Stack: ${p.techStack.join(', ')}
  Description: ${p.description}
  GitHub: ${p.githubUrl || 'N/A'}`
  )
  .join('\n\n')}

--------------------------------------------------------------------------------
EXPERIENCE & INTERNSHIPS
${student.experiences
  .map(
    (e) => `* ${e.role} — ${e.company} (${e.startDate} - ${e.endDate})
  ${e.description}
  Skills: ${e.skillsUsed.join(', ')}`
  )
  .join('\n\n')}

--------------------------------------------------------------------------------
CERTIFICATIONS
${student.certifications
  .map((c) => `* ${c.title} — ${c.issuer} (${c.issueDate}) [Credential: ${c.credentialId}]`)
  .join('\n')}

================================================================================
Generated by ARC Operating System — Official Institutional Document
Verification URL: https://arc.apex.edu.in/verify/${student.arcId}
================================================================================
`;

  return new NextResponse(resumeText, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition': `attachment; filename="${student.rollNumber}_ARC_Resume.txt"`,
    },
  });
}
